spring:
  application:
    name: authorization
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://user-db:3306/user
    username: vs
    password: test
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instance-id: "${spring.application.name}:${random.value}"

security:
  oauth2:
    resource:
      user-info-uri: http://authorization-service:8080/self