spring:
   application:
      name: catalog
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka/
   instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      metadata-map:
         instance-id: '${spring.application.name}:${random.value}'

security:
   oauth2:
      resource:
         user-info-uri: http://authorization:8080/self