server:
  port: 8082
spring:
  application:
    name: Product 
eureka:  client:    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    metadata-map:      instance-id: "${spring.application.name}:${random.value}"