eureka:
   instance:
      lease-renewal-interval-in-seconds: 10
      status-page-url-path: /info
      health-check-url-path: /health

zuul:
   ignoredServices: '*'
   routes:
      catalog: /catalog-service/**
      User: /user-service/**

hystrix:
   dashboard:
      proxy-stream-allow-list: '*'
