/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package webshop.user;

//@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-12-08T15:00:53.920Z")
//
//@RequestMapping("/user")
//public interface UserApi {
//    @RequestMapping(value = "/register",
//        produces = { "application/json" },
//        consumes = { "multipart/form-data" },
//        method = RequestMethod.PUT)
//    ResponseEntity<Boolean> register(@RequestBody LoginForm loginForm);
//
//}
